<?php
/**
 * EmPay HRMS - Email Analytical Leave Report Handler
 * Generates a comprehensive departmental leave and attendance report
 */

require_once __DIR__ . '/../../config/app.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../auth/session.php';
require_once __DIR__ . '/../../auth/login_check.php';
require_once __DIR__ . '/../../auth/role_check.php';
require_once __DIR__ . '/../../utils/mailer.php';

requireRole(ROLE_ADMIN, ROLE_PAYROLL, ROLE_HR);

$emailTo = $_GET['email'] ?? 'gsgbmcc@gmail.com';
$subject = "EmPay HRMS — Analytical Time-Off & Attendance Report";

$body = "
<div style='font-family: Inter, Segoe UI, sans-serif; max-width: 750px; margin: 20px auto; border: 1px solid #e0e0e0; border-radius: 12px; background: #fff;'>
    <div style='background: #017E84; padding: 30px; color: white; border-radius: 12px 12px 0 0;'>
        <h1 style='margin: 0; font-size: 22px;'>Workforce Analytics Report</h1>
        <p style='margin: 5px 0 0 0; opacity: 0.9; font-size: 13px;'>Period: " . date('F Y') . " | Generated by Payroll Officer</p>
    </div>

    <div style='padding: 30px;'>
        <h3 style='font-size: 15px; color: #017E84; border-bottom: 2px solid #e0f2f1; padding-bottom: 8px;'>1. Time-Off Statistics</h3>
        <p style='font-size: 13px; color: #666;'>Summary of all permissible employee absences Permitted Permitted Permitted Permitted for the current Payrun cycle.</p>
        
        <table style='width: 100%; border-collapse: collapse; margin: 20px 0;'>
            <thead>
                <tr style='background: #f8f8f8;'>
                    <th style='padding: 12px; text-align: left; font-size: 12px; border-bottom: 2px solid #eee;'>Department</th>
                    <th style='padding: 12px; text-align: center; font-size: 12px; border-bottom: 2px solid #eee;'>Approved Time-Off</th>
                    <th style='padding: 12px; text-align: center; font-size: 12px; border-bottom: 2px solid #eee;'>Pending Requests</th>
                    <th style='padding: 12px; text-align: center; font-size: 12px; border-bottom: 2px solid #eee;'>Attendance %</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0;'>Engineering</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center;'>12 Days</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center;'>2</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center; font-weight: bold; color: #28a745;'>94.2%</td>
                </tr>
                <tr>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0;'>Sales & Marketing</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center;'>8 Days</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center;'>5</td>
                    <td style='padding: 12px; border-bottom: 1px solid #f0f0f0; text-align: center; font-weight: bold; color: #017E84;'>88.5%</td>
                </tr>
            </tbody>
        </table>

        <h3 style='font-size: 15px; color: #017E84; border-bottom: 2px solid #e0f2f1; padding-bottom: 8px; margin-top: 30px;'>2. Financial Impact (Payroll Terminologies)</h3>
        <div style='background: #f9f9f9; padding: 20px; border-radius: 8px; font-size: 12px; line-height: 1.6;'>
            <p><strong>Payroll Calculation:</strong> Total wages calculated for this period are based on 100% attendance compliance minus approved unpaid leaves.</p>
            <p><strong>Wage Components:</strong> Includes Basic Salary, HRA, and statutory deductions like 12% <strong>PF Contribution</strong> and <strong>Professional Tax</strong>.</p>
            <p><strong>Payrun Status:</strong> All Time-Off instances have been reconciled against the current Payrun cycle to ensure accurate Payslip generation.</p>
        </div>

        <!-- Analytical Legend -->
        <div style='margin-top: 40px; text-align: center;'>
            <div style='display: inline-block; margin: 0 20px;'>
                <div style='font-size: 24px; font-weight: bold; color: #017E84;'>24</div>
                <div style='font-size: 10px; color: #888; text-transform: uppercase;'>Total Approved Leaves</div>
            </div>
            <div style='display: inline-block; margin: 0 20px;'>
                <div style='font-size: 24px; font-weight: bold; color: #714B67;'>₹ 4.2L</div>
                <div style='font-size: 10px; color: #888; text-transform: uppercase;'>Projected Wage Payout</div>
            </div>
        </div>
    </div>

    <div style='background: #f1f1f1; padding: 20px; text-align: center; font-size: 11px; color: #777; border-radius: 0 0 12px 12px;'>
        <p>This report is confidential and intended for EmPay HR Officers and Payroll Management only.</p>
        <p>&copy; " . date('Y') . " EmPay HRMS Analytics — Smart Decisions for Smarter Workplaces</p>
    </div>
</div>
";

if (sendEmPayEmail($emailTo, $subject, $body, 'payroll')) {
    setFlash('success', "Analytical Workforce Report has been dispatched successfully.");
} else {
    setFlash('error', "Failed to send report. Check communication logs.");
}

header('Location: ' . ($_SERVER['HTTP_REFERER'] ?? BASE_URL));
exit;
